# Generated by Django 3.0.2 on 2020-02-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='crystal_habit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mineral',
            name='refractive_index',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mineral',
            name='specific_gravity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
